# Changes here will be overwritten by Copier
_commit: 7951d1c
_src_path: python_template
github_username: dvatvani
package_name: miniball
project_description: An analytics/programmer-friendly 2D football game
